apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata:
  name: smf-example
  namespace: oai-core
spec:
  provider: smf.openairinterface.org
  parametersRefs:
  - name: oai-smf-config
    apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
