apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: du-core-f1
  namespace: oai-du
spec:
  config: '{"cniVersion":"0.3.1","name": "du-core-f1","plugins":[{"type":"macvlan","capabilities":{"ips":true}, "master":"eth0","mode":"bridge","ipam":{"type":"static"}}]}'
