apiVersion: infra.nephio.org/v1alpha1
kind: Network
metadata: # kpt-merge: /vpc-cu-e1
  name: vpc-cu-e1
  annotations:
    config.kubernetes.io/local-config: "true"
    internal.kpt.dev/upstream-identifier: 'infra.nephio.org|Network|default|vpc-cu-e1'
spec:
  topology: nephio
  routingTables:
  - name: vpc-cu-e1
    prefixes:
    - prefix: 172:4::/32
      labels:
        nephio.org/network-name: e1
    - prefix: 172.4.0.0/16
      labels:
        nephio.org/network-name: e1
    interfaces:
    - kind: bridgedomain
      bridgeDomainName: vpc-cu-e1
  bridgeDomains:
  - name: vpc-cu-e1
    interfaces:
    - kind: interface
      selector:
        matchExpressions:
        - {key: nephio.org/cluster-name, operator: Exists}
      attachmentType: vlan
