apiVersion: workload.nephio.org/v1alpha1
kind: NFDeployment
metadata: # kpt-merge: example/cucp-example
  name: cucp-example
  namespace: example
  annotations:
    internal.kpt.dev/upstream-identifier: 'workload.nephio.org|NFDeployment|example|cucp-example'
spec:
  provider: cucp.openairinterface.org
  interfaces:
  - name: n2
    ipv4:
      address: 172.18.0.22/24
      gateway: 172.18.0.1
    vlanID: 2
  - name: f1c
    ipv4:
      address: 172.18.0.23/24
      gateway: 172.18.0.1
    vlanID: 5
  - name: e1
    ipv4:
      address: 172.18.0.24/24
      gateway: 172.18.0.1
    vlanID: 1
  networkInstances:
  - name: vpc-ran
    interfaces:
    - n2
  - name: vpc-cudu-f1
    interfaces:
    - f1c
  - name: vpc-cu-e1
    interfaces:
    - e1
  parametersRefs:
  - apiVersion: workload.nephio.org/v1alpha1
    kind: NFConfig
    name: cucp-nf-config
  - name: cucp-ran-amf-core
    apiVersion: ref.nephio.org/v1alpha1
    kind: Config
