apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-up-operators
spec:
  upstream:
    repo: oai-core-packages-custom
    package: oai-up-operators
    revision: v2.0.0
  downstream:
    repo: core
    package: oai-up-operators
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core