apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: oai-ran-operator-edge
spec:
  upstream:
    repo: catalog-workloads-oai-ran
    package: oai-ran-operator
    revision: v2.0.0
  downstream:
    repo: core
    package: oai-ran-operator
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core