apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: core-oai-smf
spec:
  upstream:
    repo: oai-packages
    package: oai-smf
    revision: v2.0.0
  downstream:
    repo: oai-core-packages-custom
    package: oai-smf
  annotations:
    approval.nephio.org/policy: initial
    
