apiVersion: config.porch.kpt.dev/v1alpha1
kind: PackageVariant
metadata:
  name: edge-oai-upf
spec:
  upstream:
    repo: oai-core-packages-custom
    package: oai-upf
    revision: v4
  downstream:
    repo: core
    package: oai-upf
  annotations:
    approval.nephio.org/policy: initial
  injectors:
  - name: core
