apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  name: cuup-example-f1u
  namespace: example
spec:
  config: '{"cniVersion":"0.3.1","name": "cuup-example-f1u","plugins":[{"type":"macvlan","capabilities":{"ips":true},"master":"eth0","mode":"bridge","ipam":{"type":"static"}}]}'
